const dummyEmails = [
    {
        _id: "1",
        senderName: "Bob",
        senderAddress: "bob@gmail.com",
        title: "Job Application",
        body: "Dear Hiring Manager, \n I hope you’re doing well. I am writing to express my interest in the Software Engineer position at TechCorp. With my background in full-stack development, I am excited about the opportunity to contribute to your team. \n I have attached my resume for your review. I would love the chance to discuss how my skills align with this role. \n Best regards, Bob",
        attachments: [
            { title: "My CV", body: "some binary file" },
            { title: "My Cover Letter", body: "some binary file" },
        ],
        timestamp: "2024-01-31T10:00:00.000Z",
    },
    {
        _id: "2",
        senderName: "Charlie",
        senderAddress: "charlie@gmail.com",
        title: "Job Offer",
        body: "Dear Bob, \n We are pleased to offer you the position of Software Engineer at TechCorp. Please find the contract attached. \n Best regards, HR Team",
        attachments: [{ title: "Contract", body: "some binary file" }],
        timestamp: "2024-01-31T11:00:00.000Z",
    },
    {
        _id: "3",
        senderName: "Alice",
        senderAddress: "alice@gmail.com",
        title: "Meeting Reminder",
        body: "Hi Team, \n Just a reminder about our meeting scheduled for tomorrow at 10 AM. \n Best, Alice",
        attachments: [],
        timestamp: "2024-02-01T09:00:00.000Z",
    },
    {
        _id: "4",
        senderName: "David",
        senderAddress: "david@gmail.com",
        title: "Project Update",
        body: "Hi Team, \n Here is the latest update on our project. \n Regards, David",
        attachments: [{ title: "Project Report", body: "some binary file" }],
        timestamp: "2024-02-02T14:30:00.000Z",
    },
    {
        _id: "5",
        senderName: "Eve",
        senderAddress: "eve@gmail.com",
        title: "Invoice Attached",
        body: "Dear Client, \n Please find the attached invoice for your reference. \n Best, Eve",
        attachments: [{ title: "Invoice", body: "some binary file" }],
        timestamp: "2024-02-03T16:45:00.000Z",
    },
    {
        _id: "6",
        senderName: "Frank",
        senderAddress: "frank@gmail.com",
        title: "Feedback Request",
        body: "Hello, \n We would appreciate your feedback on our recent service. \n Thanks, Frank",
        attachments: [],
        timestamp: "2024-02-04T08:20:00.000Z",
    },
    {
        _id: "7",
        senderName: "Grace",
        senderAddress: "grace@gmail.com",
        title: "Event Invitation",
        body: "Dear All, \n You are invited to our annual company event. Please RSVP. \n Regards, Grace",
        attachments: [{ title: "Event Brochure", body: "some binary file" }],
        timestamp: "2024-02-05T12:10:00.000Z",
    },
    {
        _id: "8",
        senderName: "Henry",
        senderAddress: "henry@gmail.com",
        title: "System Maintenance Notice",
        body: "Dear Users, \n Our system will undergo maintenance on Saturday from 1 AM to 3 AM. \n Regards, IT Team",
        attachments: [],
        timestamp: "2024-02-06T15:00:00.000Z",
    },
    {
        _id: "9",
        senderName: "Isla",
        senderAddress: "isla@gmail.com",
        title: "New Product Launch",
        body: "Dear Customers, \n We are excited to announce our new product launch. Check the details inside. \n Best, Isla",
        attachments: [{ title: "Product Catalog", body: "some binary file" }],
        timestamp: "2024-02-07T17:30:00.000Z",
    },
    {
        _id: "10",
        senderName: "Jack",
        senderAddress: "jack@gmail.com",
        title: "Holiday Greetings",
        body: "Dear Team, \n Wishing you all a Happy New Year! \n Cheers, Jack",
        attachments: [],
        timestamp: "2024-02-08T20:00:00.000Z",
    },
    {
        _id: "11",
        senderName: "Karen",
        senderAddress: "karen@gmail.com",
        title: "Survey Request",
        body: "Hi, \n Please take a moment to complete our survey. \n Thanks, Karen",
        attachments: [],
        timestamp: "2024-02-09T13:25:00.000Z",
    },
    {
        _id: "12",
        senderName: "Liam",
        senderAddress: "liam@gmail.com",
        title: "Newsletter - February Edition",
        body: "Hello, \n Check out our latest newsletter for updates. \n Regards, Liam",
        attachments: [{ title: "Newsletter", body: "some binary file" }],
        timestamp: "2024-02-10T10:50:00.000Z",
    },
    {
        _id: "13",
        senderName: "Mia",
        senderAddress: "mia@gmail.com",
        title: "Account Update",
        body: "Dear User, \n Your account details have been updated. \n Regards, Support Team",
        attachments: [],
        timestamp: "2024-02-11T18:15:00.000Z",
    },
    {
        _id: "14",
        senderName: "Noah",
        senderAddress: "noah@gmail.com",
        title: "Workshop Registration",
        body: "Dear Attendee, \n Your registration for the workshop is confirmed. \n Regards, Noah",
        attachments: [],
        timestamp: "2024-02-12T09:40:00.000Z",
    },
    {
        _id: "15",
        senderName: "Olivia",
        senderAddress: "olivia@gmail.com",
        title: "Billing Issue",
        body: "Dear Customer, \n We noticed an issue with your recent payment. Please contact support. \n Regards, Olivia",
        attachments: [],
        timestamp: "2024-02-13T14:00:00.000Z",
    },
    {
        _id: "16",
        senderName: "Paul",
        senderAddress: "paul@gmail.com",
        title: "Team Outing",
        body: "Hey Team, \n We are planning a team outing this weekend. Let us know if you can join. \n Cheers, Paul",
        attachments: [],
        timestamp: "2024-02-14T16:20:00.000Z",
    },
    {
        _id: "17",
        senderName: "Quinn",
        senderAddress: "quinn@gmail.com",
        title: "Security Alert",
        body: "Dear User, \n We detected a login from a new device. If this was not you, please reset your password. \n Regards, Security Team",
        attachments: [],
        timestamp: "2024-02-15T19:00:00.000Z",
    },
    {
        _id: "18",
        senderName: "Rachel",
        senderAddress: "rachel@gmail.com",
        title: "Performance Review",
        body: "Hi, \n Your performance review has been scheduled for next Monday. \n Regards, HR Team",
        attachments: [],
        timestamp: "2024-02-16T08:30:00.000Z",
    },
    {
        _id: "19",
        senderName: "Steve",
        senderAddress: "steve@gmail.com",
        title: "Webinar Invitation",
        body: "Hello, \n You are invited to our upcoming webinar on AI advancements. Please register soon. \n Regards, Steve",
        attachments: [{ title: "Webinar Details", body: "some binary file" }],
        timestamp: "2024-02-17T12:45:00.000Z",
    },
    {
        _id: "20",
        senderName: "Tom",
        senderAddress: "tom@gmail.com",
        title: "Technical Support Ticket",
        body: "Dear User, \n Your support ticket has been received. We will get back to you shortly. \n Regards, Support Team",
        attachments: [],
        timestamp: "2024-02-18T14:10:00.000Z",
    },
    {
        _id: "21",
        senderName: "Uma",
        senderAddress: "uma@gmail.com",
        title: "Payment Confirmation",
        body: "Dear Customer, \n Your payment has been successfully processed. Thank you for your business! \n Regards, Finance Team",
        attachments: [],
        timestamp: "2024-02-19T10:15:00.000Z",
    },
    {
        _id: "22",
        senderName: "Victor",
        senderAddress: "victor@gmail.com",
        title: "Service Downtime Notice",
        body: "Dear Users, \n We will have a scheduled downtime for maintenance this weekend. Apologies for any inconvenience. \n Regards, IT Team",
        attachments: [],
        timestamp: "2024-02-20T11:45:00.000Z",
    },
    {
        _id: "23",
        senderName: "Wendy",
        senderAddress: "wendy@gmail.com",
        title: "New Policy Update",
        body: "Hello Team, \n Please review the updated company policies attached. Let us know if you have any questions. \n Best, Wendy",
        attachments: [{ title: "Policy Document", body: "some binary file" }],
        timestamp: "2024-02-21T13:00:00.000Z",
    },
    {
        _id: "24",
        senderName: "Xavier",
        senderAddress: "xavier@gmail.com",
        title: "Conference Registration",
        body: "Dear Attendee, \n Your registration for the upcoming tech conference is confirmed. See details inside. \n Regards, Xavier",
        attachments: [{ title: "Conference Agenda", body: "some binary file" }],
        timestamp: "2024-02-22T14:20:00.000Z",
    },
    {
        _id: "25",
        senderName: "Yara",
        senderAddress: "yara@gmail.com",
        title: "Reminder: Subscription Renewal",
        body: "Dear User, \n Your subscription is about to expire. Please renew to continue enjoying our services. \n Regards, Support Team",
        attachments: [],
        timestamp: "2024-02-23T16:30:00.000Z",
    },
    {
        _id: "26",
        senderName: "Zane",
        senderAddress: "zane@gmail.com",
        title: "Interview Scheduled",
        body: "Dear Candidate, \n Your interview has been scheduled for Monday at 10 AM. Best of luck! \n Regards, HR Team",
        attachments: [],
        timestamp: "2024-02-24T18:00:00.000Z",
    },
    {
        _id: "27",
        senderName: "Anna",
        senderAddress: "anna@gmail.com",
        title: "Product Feedback Request",
        body: "Hi, \n We would love to hear your feedback on our new product. Let us know your thoughts! \n Thanks, Anna",
        attachments: [],
        timestamp: "2024-02-25T09:50:00.000Z",
    },
    {
        _id: "28",
        senderName: "Brian",
        senderAddress: "brian@gmail.com",
        title: "Support Ticket Resolved",
        body: "Dear Customer, \n Your support ticket has been resolved. Let us know if you need any further assistance. \n Regards, Support Team",
        attachments: [],
        timestamp: "2024-02-26T12:25:00.000Z",
    },
    {
        _id: "29",
        senderName: "Carla",
        senderAddress: "carla@gmail.com",
        title: "Thank You for Your Order",
        body: "Dear Customer, \n Thank you for your purchase! Your order will be shipped soon. \n Regards, Carla",
        attachments: [{ title: "Order Receipt", body: "some binary file" }],
        timestamp: "2024-02-27T14:40:00.000Z",
    },
    {
        _id: "30",
        senderName: "Derek",
        senderAddress: "derek@gmail.com",
        title: "Exclusive Offer Just for You",
        body: "Hello, \n We have an exclusive offer for our loyal customers. Check the details inside! \n Best, Derek",
        attachments: [{ title: "Discount Coupon", body: "some binary file" }],
        timestamp: "2024-02-28T17:15:00.000Z",
    },
];

module.exports = { dummyEmails };
